package main

import (
	"crypto/md5"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
)

// --- Models ---

type Config struct {
	NavidromeURL string `json:"navidrome_url"`
	Username     string `json:"username"`
	Password     string `json:"password"`
	MusicRoot    string `json:"music_root"` // e.g., /Volumes/Files - SSD/Music/
}

type SmartPlaylist struct {
	Name      string       `json:"name"` // Playlist title
	Comment   string       `json:"comment,omitempty"`
	Rules     PlaylistRule `json:"rules"`
}

type PlaylistRule struct {
	All []Rule `json:"all,omitempty"`
	Any []Rule `json:"any,omitempty"`
}

type Rule struct {
	Name     string      `json:"name"`     // Changed from 'column' to match Navidrome schema
	Operator string      `json:"operator"` // e.g., 'is', 'contains', 'startsWith'
	Value    interface{} `json:"value"`
}

// --- Subsonic Client ---

type SubsonicClient struct {
	BaseURL  string
	Username string
	Password string
}

// GenerateAuthParams creates the required Subsonic auth tokens (u, t, s)
func (c *SubsonicClient) GenerateAuthParams() (string, error) {
	saltBytes := make([]byte, 6)
	if _, err := rand.Read(saltBytes); err != nil {
		return "", fmt.Errorf("failed to generate random salt: %w", err)
	}
	salt := hex.EncodeToString(saltBytes)
	
	tokenRaw := c.Password + salt
	hasher := md5.New()
	hasher.Write([]byte(tokenRaw))
	token := hex.EncodeToString(hasher.Sum(nil))
	
	// API version 1.16.1 is standard for modern Navidrome
	return fmt.Sprintf("u=%s&t=%s&s=%s&v=1.16.1&c=SmartyP", c.Username, token, salt), nil
}

// GenerateSmartJSON constructs the playlist definition.
func (c *SubsonicClient) GenerateSmartJSON(playlistName string, relativePath string, minRating int) ([]byte, error) {
	// Navidrome Smart Playlist Logic
	rules := []Rule{
		{Name: "path", Operator: "startsWith", Value: relativePath},
		{Name: "rating", Operator: "gt", Value: minRating - 1}, // "gt 3" == 4 stars or higher
	}

	sp := SmartPlaylist{
		Name:    playlistName,
		Comment: fmt.Sprintf("Auto-generated by SmartyP for path: %s", relativePath),
		Rules: PlaylistRule{
			All: rules,
		},
	}

	return json.MarshalIndent(sp, "", "  ")
}

// --- Logic & Helpers ---

// mapToNavidromePath ensures the path is relative to the Music folder.
// e.g., /Volumes/Data/Music/Rock -> Rock
func mapToNavidromePath(fullPath, root string) string {
	rel, err := filepath.Rel(root, fullPath)
	if err != nil {
		return fullPath // Fallback
	}
	if rel == "." {
		return ""
	}
	return rel
}

// GetFolders scans the music root and returns Tier 1 and Tier 2 (for Xmas)
// It returns the full absolute path so we can map it later.
func GetFolders(root string) ([]string, error) {
	var folders []string
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil, err
	}

	for _, entry := range entries {
		if entry.IsDir() && !strings.HasPrefix(entry.Name(), ".") {
			fullPath := filepath.Join(root, entry.Name())
			folders = append(folders, fullPath)
			
			// Tier 2 logic for Xmas
			if entry.Name() == "Xmas" {
				subs, subErr := os.ReadDir(fullPath)
				if subErr != nil {
					log.Printf("Warning: failed to read Xmas subdirectories: %v", subErr)
				} else {
					for _, sub := range subs {
						if sub.IsDir() && !strings.HasPrefix(sub.Name(), ".") {
							folders = append(folders, filepath.Join(fullPath, sub.Name()))
						}
					}
				}
			}
		}
	}
	return folders, nil
}

// getAllowedOrigins returns the list of allowed CORS origins from environment or defaults
func getAllowedOrigins() []string {
	if origins := os.Getenv("CORS_ALLOWED_ORIGINS"); origins != "" {
		return strings.Split(origins, ",")
	}
	// Default allowlist for development
	return []string{"http://localhost:3000", "http://localhost:5173"}
}

// isOriginAllowed checks if the given origin is in the allowlist
func isOriginAllowed(origin string, allowlist []string) bool {
	for _, allowed := range allowlist {
		if strings.TrimSpace(allowed) == origin {
			return true
		}
	}
	return false
}

// enableCors middleware to allow the React frontend to talk to Go
func enableCors(next http.HandlerFunc) http.HandlerFunc {
	allowedOrigins := getAllowedOrigins()
	return func(w http.ResponseWriter, r *http.Request) {
		origin := r.Header.Get("Origin")
		if origin != "" && isOriginAllowed(origin, allowedOrigins) {
			w.Header().Set("Access-Control-Allow-Origin", origin)
		}
		w.Header().Set("Access-Control-Allow-Methods", "POST, GET, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Content-Type")
		if r.Method == "OPTIONS" {
			w.WriteHeader(http.StatusOK)
			return
		}
		next(w, r)
	}
}

// --- API Handlers ---

func main() {
	// Simple config loader
	config := Config{
		NavidromeURL: os.Getenv("NAVIDROME_URL"),
		Username:     os.Getenv("NAVIDROME_USER"),
		Password:     os.Getenv("NAVIDROME_PASS"),
		MusicRoot:    "/Volumes/Files - SSD/Music", // Ensure no trailing slash for cleaner Rel() logic
	}

	// Override root if env var is set (good for testing)
	if envRoot := os.Getenv("MUSIC_ROOT"); envRoot != "" {
		config.MusicRoot = envRoot
	}

	client := &SubsonicClient{
		BaseURL:  config.NavidromeURL,
		Username: config.Username,
		Password: config.Password,
	}

	http.HandleFunc("/api/folders", enableCors(func(w http.ResponseWriter, r *http.Request) {
		absFolders, err := GetFolders(config.MusicRoot)
		
		// Convert absolute paths to Navidrome relative paths for the frontend
		var relativeFolders []string
		if err != nil {
			// Fallback mock data
			relativeFolders = []string{"Musically", "Rock", "Soundtracks", "Xmas/Traditional", "Xmas/Modern"}
		} else {
			for _, abs := range absFolders {
				relativeFolders = append(relativeFolders, mapToNavidromePath(abs, config.MusicRoot))
			}
		}
		
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(relativeFolders)
	}))

	http.HandleFunc("/api/generate", enableCors(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			w.Header().Set("Allow", "POST")
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}

		var req struct {
			Name      string `json:"name"`
			Path      string `json:"path"`
			MinRating int    `json:"minRating"`
		}
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}

		// The Path coming from frontend is already relative (e.g. "Rock")
		data, err := client.GenerateSmartJSON(req.Name, req.Path, req.MinRating)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		w.Header().Set("Content-Type", "application/json")
		w.Write(data)
	}))

	fmt.Println("SmartyP Server starting on :8080...")
	if err := http.ListenAndServe(":8080", nil); err != nil {
		log.Fatalf("Server failed to start: %v", err)
	}
}